spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodhealth?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 20040816Ywj
# redis:
#  host: localhost
#  port: 6379
#  password: 20040816Ywj
#  lettuce:
#    pool:
#     max-active: 8
#     max-idle: 8
#     min-idle: 0
#     max-wait: 100
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
server:
  port: 8081